expires_time = 360000
use_oauth = False
oauth_bypass_magic_code = 'oauth_magic_code'
secret_key = 'my secret'
token_type = 'Bearer'
oauth_url = 'http://api.mooctest.net/oauth/token'
oauth_token_type = 'Basic'
oauth_token = 'TW9vY3Rlc3REYXRhQXNzZXNzbWVudDpNb29jdGVzdERhdGFBc3Nlc3NtZW50'
oauth_grant_type = 'authorization_code'
oauth_redirect_uri = 'http://mooctest.whiskychoy.org/auth/mooctest/callback'
oauth_scope = 'read'
user_url = 'http://api.mooctest.net/oauth/api/user'
oauth_bypass_username = '王德发'
oauth_bypass_open_id = 'c0537dd8a9554dc6a54a8586ecf6c9df'
